import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "./globals.css";

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
  weight: ["400", "700", "800"],
  style: ["normal"],
  display:'swap'
});


export const metadata: Metadata = {
  title: "Minhaz Fardin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${funnelDisplay.variable} antialiased bg-black`}>
        {children}
      </body>
    </html>
  );
}
